import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import NavbarWrapper from "@/components/layout/NavbarWrapper";
import ClientThemeProvider from "@/components/providers/ClientThemeProvider";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import "react-multi-carousel/lib/styles.css";
import { FormDataProvider } from "@/context/FormDataContext";
import "./globals.css";
import FooterWrapper from "@/components/layout/FooterWrapper";

export const metadata = {
  icons: {
    icon: "/icon.png",
  },
  title: "Madmon",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  const direction = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={direction}>
      <body>
        <ReactQueryProvider>
          <NextIntlClientProvider messages={messages}>
            <ClientThemeProvider direction={direction}>
              <NavbarWrapper />
              <FormDataProvider>
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    minHeight: "100vh",
                  }}
                >
                  <main style={{ flex: 1 }}>{children}</main>
                  <FooterWrapper />
                </div>
              </FormDataProvider>
            </ClientThemeProvider>
          </NextIntlClientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}

